function tracking_data = getBehData(tracking_data, beh_data)

%Copy data relevant to tracking analysis from behavior file
load(beh_data,'data');
tracking_data.DLC.t = data.raw.X';

%Copy over specified vars from behavioral data struct
vars = {'N','laserSide',...
    'trialStart','nosePokeEntry','nosePokeExit','leverPresentation','leverPress',...
    'rewardDelivery','rewardEntry','rewardExit',...
    'cue','choice','reward','rt'...
    'leftProb','rightProb','laserOn','laserOff',...
    'trialIdx_all','trialIdx_laser','trialIdx_multilaser','trialIdx_laserPrev',...
    'multiRewIdx','multiPrevRewIdx','multiPrevNRewIdx',...
};

%Populate tracking data struct
for i = 1:numel(vars)
    tracking_data.trialData.(vars{i}) = data.(vars{i});
end